name: aurora_build
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extra_pedantic: ^4.0.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  get_it: ^7.6.1
  injectable: ^2.3.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  camera: ^0.10.5
  camera_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: camera_aurora-0.5.0
      path: packages/camera/camera_aurora
  logger: ^2.2.0
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.5.0
      path: packages/path_provider/path_provider_aurora
  internal_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: internal_aurora-0.5.0
      path: packages/internal_aurora
  shared_preferences_aurora:
    path: shared_preferences_aurora
  i18n:
    path: i18n
  ui_application:
    path: ui_application
  path_provider: ^2.0.15

  

dev_dependencies:
  build_runner: ^2.4.9
  injectable_generator: ^2.3.0

flutter:
  uses-material-design: true