# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
name: shared_preferences_aurora
description: The Aurora OS implementation of shared_preferences.
version: 0.5.0

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.1.1
  shared_preferences_platform_interface: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.5.0
      path: packages/path_provider/path_provider_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        dartPluginClass: SharedPreferencesAurora
